### ISSUE TITLE
newlineMaximum failing

### ISSUE THREAD

**Issue by Splact** [schorfES/grunt-lintspaces#22]
I get this error: "Maximum amount of newlines exceeded. Found 2 newlines, expected maximum is 3"

I want accept this kind of situation:

``` javascript
function pee(arg) {
  //
}


function poo(arg) {
  //
}
```

This works only when I set the newlineMaximum to 5 or higher.

**Comment by schorfES** [comment]
Hopefully fixed in version 0.7.1! Let me know!

**Comment by schorfES** [comment]
Is this issue obsolete?
